// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmmwcpjcglxllemqjsmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtbXdjcGpjZ2x4bGxlbXFqc21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTU2MDYsImV4cCI6MjA2NTkzMTYwNn0.4-r-rJUHPDYekeKZYPcSANtswf_XE2ETMdPoG_5PEAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);